config.single_export_download:
  path: '/admin/config/development/configuration/single/export-download/{filename}'
  defaults:
    _controller: '\Drupal\config_single_export\Controller\ConfigSingleExportController::downloadSingleExport'
  options:
    parameters:
      filename:
        type: string
  requirements:
    _permission: 'export configuration'
